### ISSUE TITLE
master compilation failure due to undef'd fontbase

### ISSUE THREAD

**Issue by markcmiller86** [GLVis/glvis#52]
I happened to download master because I needed a cmake-enabled glvis.

I tried to build on OSX 10.11.6. I had to turn off PNG and FREETYPE due to...

```
ld: warning: ld: warning: ignoring file /sw/lib/libpng.dylib, file was built for i386 which is not the architecture being linked (x86_64): /sw/lib/libpng.dylibignoring file /sw/lib/libfreetype.dylib, file was built for i386 which is not the architecture being linked (x86_64): /sw/lib/libfreetype.dylib
```
But, then I ran into this error...
```
/Users/miller86/fastmath/atpesc17_examples/mfem/glvis/lib/vssolution.cpp:1020:16: error: use of undeclared identifier 'fontbase'
```
Adding ``extern GLuint fontbase;`` declaration to to vssolution.cpp fixes

**Comment by tzanio** [comment]
Can this be due to a previous installation that you upgraded over?

On my Macs (10.11.6 and 10.12.6) both `libpng` and `libfreetype` are available in `/opt/X11/lib/`.

Can you make sure you have them there too (I think they come with `XQuartz`) and try listing that before `/sw/lib` in your path?

**Comment by markcmiller86** [comment]
I supposed it could be. However, that doesn't change the fact there is a clear bug in vssolution.cpp missing the extern for fontbase when PNG and FREETYPE are turned off.
