### PR TITLE
Update C++ standard to 17

### LINKED ISSUE #347: CMake compile fails without C++17 Standard
Hi,

I am unable to compile GLVis using CMake with the current master branches of both unless I update the CXX standard in CMakeLists.txt from

```
set(CMAKE_CXX_STANDARD 11)
```

to

```
set(CMAKE_CXX_STANDARD 17)
```

The build fails with all errors related to not using C++17, like:

```
In file included from /home/j-signorelli/software/mfem/git_repo/linalg/linalg.hpp:40,
                 from /home/j-signorelli/software/mfem/git_repo/mfem.hpp:45,
                 from /home/j-signorelli/software/mfem/git_repo/build/mfem.hpp:3,
                 from /home/j-signorelli/software/mfem/glvis/lib/gl/../openglvis.hpp:19,
                 from /home/j-signorelli/software/mfem/glvis/lib/gl/../aux_vis.hpp:18,
                 from /home/j-signorelli/software/mfem/glvis/lib/gl/renderer_core.cpp:14:
/home/j-signorelli/software/mfem/git_repo/linalg/filteredsolver.hpp: In constructor ‘mfem::AMGFSolver::AMGFSolver()’:
/home/j-signorelli/software/mfem/git_repo/linalg/filteredsolver.hpp:130:18: error: ‘make_unique’ is not a member of ‘std’
  130 |       amg = std::make_unique<HypreBoomerAMG>();
      |                  ^~~~~~~~~~~
/home/j-signorelli/software/mfem/git_repo/linalg/filteredsolver.hpp:130:18: note: ‘std::make_unique’ is only available from C++14 onwards
```

Should this be updated since MFEM now uses C++17? Or is there something I am doing wrong on my end?

Thanks for any input!

### PR DESCRIPTION
**Pull request by j-signorelli**
Closes #347

### CODE REVIEW

**Comment by najlkin** [comment]
Nope, it comes from somewhere else due to the namespace pollution 🫤 . I have cleaned that up in #336 , so I transplanted that here. Let us see if it works...

**Comment by j-signorelli** [comment]
Thanks so much @najlkin for looking into this

**Comment by najlkin** [comment]
It works! 🎉

**Review by najlkin — APPROVED** [review]

**Review by tzanio — APPROVED** [review]
Thanks @najlkin !

File: CMakeLists.txt [hunk 1]
```diff
@@ -13,7 +13,7 @@
 # introduced.
 cmake_minimum_required(VERSION 3.10)
 
-set(CMAKE_CXX_STANDARD 11)
+set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_CXX_STANDARD_REQUIRED ON)
 set(CMAKE_CXX_EXTENSIONS OFF)
```
Comment (helloworld922) [inline CMakeLists.txt:18]: With https://github.com/mfem/mfem/pull/5163 these three lines can be removed and glvis can just track mfem's C++ version. Should be fine to leave these for now so users can build with the 4.9 release.
